extends Node
## Single source of truth for all tunable game constants.
## All other modules read numeric values from here — no magic numbers elsewhere.


# === Constants ===

# --- Campaign Structure ---
const HOUSES_PER_VILLAGE: int = 5
const VILLAGES_PER_CAMPAIGN: int = 5

# --- Draft ---
const STARTER_DRAFT_SIZE: int = 5
const TOWER_DRAFT_SIZE: int = 5

# --- Morale ---
const MORALE_MIN: int = -2
const MORALE_MAX: int = 2
const MORALE_SHIFT_PER_ESCAPE: int = 1      # added per escaped villager
const MORALE_SHIFT_PER_INFECTION: int = 1   # subtracted per infected/killed villager

# --- Villager Movement ---
const VILLAGER_BASE_SPEED: float = 80.0        # BALANCE: world units per second
const VILLAGER_SPEED_FLOOR: float = 0.2        # BALANCE: minimum as fraction of base speed

# --- Desperate State ---
const DESPERATE_STATE_DELAY: float = 2.0       # BALANCE: seconds before Desperate triggers with no path

# --- Barricade ---
const BARRICADE_HP: float = 100.0              # BALANCE
const DEMOLISH_RATE: float = 10.0             # BALANCE: HP damage per tick per villager
const DEMOLISH_TICK_INTERVAL: float = 1.0     # BALANCE: seconds between demolish damage ticks

# --- Rot ---
const ROT_THRESHOLD: int = 5                  # BALANCE: stacks to trigger explosion
const ROT_TRANSFER_PCT: float = 0.5           # BALANCE: fraction of stacks transferred on explosion

# --- Hex Grid (pointy-top, oddr offset) ---
const HEX_SIZE: float = 64.0             # circumradius (center to vertex)
const TILE_HALF_WIDTH: float = 64.0      # used as stop-distance in villager movement
const GRID_WIDTH: int = 15
const GRID_HEIGHT: int = 15

# --- Infection ---
const INFECTION_TICK_RATE: float = 1.0        # BALANCE: seconds between ticks

# --- Tech Tree ---
const TECH_POINTS_PER_WAVE: int = 1           # BALANCE: points awarded per completed wave
const TECH_NODE_COST: int = 1                  # BALANCE: points to purchase any tech node
const TECH_STAT_DELTA: float = 0.1             # BALANCE: generic stat increase per stat-node purchase
const TECH_CHAIN_COUNT_DELTA: int = 1          # BALANCE: chain_count increase per chain_count purchase

# --- Wave Spawn ---
const WAVE_SPAWN_BATCH_SIZE: int = 2            # BALANCE: villagers spawned per batch
const WAVE_SPAWN_INTERVAL: float = 0.8          # BALANCE: seconds between spawn batches
const WAVE_SCALE_PER_HOUSE: float = 0.3         # BALANCE: additive wave size multiplier per house cleared

# --- Modifier Deck ---
const MODIFIER_DECK_SIZE: int = 25
# Cards dealt per village — index matches village_index (0–4)
const MODIFIER_CARDS_PER_VILLAGE: Array[int] = [0, 1, 2, 3, 4]

# --- Village Scaling (index = village_index 0–4) ---
const VILLAGE_HP_MULTIPLIERS: Array[float] = [1.0, 1.2, 1.5, 1.8, 2.2]          # BALANCE
const VILLAGE_COUNT_MULTIPLIERS: Array[float] = [1.0, 1.3, 1.6, 2.0, 2.6]       # BALANCE (per GDD)

# --- House Scaling (index = house_position 0–4) ---
const HOUSE_POSITION_MULTIPLIERS: Array[float] = [1.0, 1.3, 1.7, 2.2, 2.8]      # BALANCE (per GDD)
const VILLAGER_BASE_COUNT: int = 5                   # BALANCE: Standard villager count, House 1, Village 1
const ARCHETYPE_SIGNATURE_RATIO: float = 0.7         # BALANCE: fraction of wave that is the signature archetype

# --- Village Layout ---
## Exit tiles are generated by VillageGenerator along the right edge column.
const EXIT_COUNT_MIN: int = 1         # minimum exits per village
const EXIT_COUNT_MAX: int = 3         # maximum exits per village
const EXIT_MIN_SEPARATION: int = 3    # minimum tile distance between two exits on the same edge
const HOUSE_MIN_SEPARATION: int = 4              # min Manhattan-distance between house spawn tiles
const EXIT_MARGIN_TILES: int = 3                 # tiles reserved on exit side (houses won't spawn here)
const HOUSE_PLACEMENT_ATTEMPTS: int = 100        # rejection-sampling attempts before forced placement
const OBSTACLE_COUNT_BASE: int = 10              # BALANCE: target number of static obstacles per village
const OBSTACLE_GEN_ATTEMPTS: int = 50            # max iterations when placing obstacles

# --- Modular Village Generation ---
## Feature flag — when true, VillageGenerator builds villages from skeleton + modules + filler.
## When false, falls back to the original purely-procedural placement.
const USE_MODULAR_GENERATION: bool = true
## Fraction of remaining walkable tiles that may receive a filler obstacle in modular mode.
const MODULAR_FILLER_DENSITY: float = 0.12        # BALANCE
## Max attempts when assigning a module to a slot before leaving the slot empty.
const MODULE_ASSIGNMENT_ATTEMPTS: int = 8

# --- Archetype HP Ratios (relative to Standard villager base HP) ---
const ARCHETYPE_HP_RATIOS: Dictionary = {
	&"standard":    1.0,
	&"child":       0.6,   # BALANCE
	&"elder":       0.8,   # BALANCE
	&"guard":       1.5,   # BALANCE
	&"priest":      0.8,   # BALANCE
	&"doctor":      0.8,   # BALANCE
	&"gravedigger": 1.2,   # BALANCE
}

# --- Archetype Base Speeds (multiplier of VILLAGER_BASE_SPEED) ---
const ARCHETYPE_SPEED_MULTIPLIERS: Dictionary = {
	&"standard":    1.0,
	&"child":       1.4,   # BALANCE: fastest
	&"elder":       0.7,   # BALANCE: slowest
	&"guard":       0.85,  # BALANCE
	&"priest":      0.9,   # BALANCE
	&"doctor":      0.9,   # BALANCE
	&"gravedigger": 0.75,  # BALANCE
}

# --- Elder Aura ---
const ELDER_AURA_RADIUS: float = 96.0         # BALANCE: world units
const ELDER_SPEED_BONUS: float = 0.2          # BALANCE: additive fraction of base speed

# --- Guard ---
const GUARD_SHIELD_HP: float = 60.0           # BALANCE
const GUARD_SHIELD_RADIUS: float = 80.0       # BALANCE: zero-damage zone radius

# --- Priest / Doctor Aura ---
const PRIEST_AURA_RADIUS: float = 96.0        # BALANCE
const DOCTOR_AURA_RADIUS: float = 96.0        # BALANCE
const PRIEST_RESISTANCE_BONUS: float = 0.3    # BALANCE: Pestilence resistance fraction
const DOCTOR_RESISTANCE_BONUS: float = 0.3    # BALANCE: Blight resistance fraction

# --- Gravedigger ---
const GRAVEDIGGER_FLAT_RESISTANCE: float = 0.2  # BALANCE: flat resistance to all types

# --- Child Pathfinding ---
const CHILD_SOLID_SPEED_PENALTY: float = 0.4   # BALANCE: speed fraction while overlapping solids

# --- Tower Type Sets ---
const BASE_TOWER_TYPES: Array[StringName] = [
	&"blight", &"plague", &"pestilence", &"miasma", &"festering"
]

# Combine table — keys are alphabetically sorted type pairs joined by "|"
# Used by DraftManager to resolve valid Combine options and by TechTreeManager for Discovery branches
const SYNTHESIS_COMBINE_TABLE: Dictionary = {
	"blight|festering":    &"corpse_bloom",
	"blight|miasma":       &"shroud",
	"blight|pestilence":   &"epidemic",
	"blight|plague":       &"wither",
	"festering|miasma":    &"necrotic",
	"festering|pestilence": &"plague_pit",
	"festering|plague":    &"fester_burst",
	"miasma|pestilence":   &"pandemic",
	"miasma|plague":       &"septic",
	"pestilence|plague":   &"virulence",
}

# --- Tower Attack Geometry ---
const TOWER_CHAIN_HOP_RANGE: float = 220.0     # BALANCE: max distance between chain hops (world units; ~2 hex widths)
const TOWER_LINE_HALF_WIDTH: float = 20.0      # BALANCE: half-width of Line shape raycast (world units)
const TOWER_MIN_FIRE_RATE: float = 0.1         # BALANCE: minimum fire rate floor after stat upgrades (seconds)

# --- Tower Placeholder Defaults (used by factory until .tres data assets exist) ---
const TOWER_DEFAULT_RANGE: float = 250.0       # BALANCE: world units
const TOWER_DEFAULT_FIRE_RATE: float = 1.0     # BALANCE: seconds between attacks
const TOWER_DEFAULT_BASE_DAMAGE: float = 20.0  # BALANCE: base damage per tick

# --- Pestilence Spread ---
const PESTILENCE_SPREAD_DEFAULT_TICKS: int = 5  # BALANCE: fallback tick count for freshly spread DoT

# --- Rot Carrier Transmission ---
const ROT_CARRIER_RANGE: float = 80.0          # BALANCE: transmission radius in world units
const ROT_CARRIER_CHANCE: float = 0.15         # BALANCE: stack transfer chance per tick per nearby villager
const ROT_CARRIER_STACKS_PER_TICK: int = 1     # BALANCE: stacks transmitted per successful roll

# --- Villager HP ---
const VILLAGER_BASE_HP: float = 100.0          # BALANCE: Standard archetype max HP

# --- Guard Shield ---
const GUARD_SHIELD_DRAIN_RATE: float = 5.0     # BALANCE: shield HP drained per second

# --- Infection Effect Types (all named types in the game) ---
const INFECTION_EFFECT_TYPES: Array[StringName] = [
	&"plague", &"blight", &"pestilence", &"miasma", &"necrotic"
]

# --- Festering Ground Patch ---
const FESTERING_PATCH_RADIUS: float = 60.0       # BALANCE: contact radius in world units
const FESTERING_PATCH_DURATION: float = 5.0      # BALANCE: seconds the patch persists
const FESTERING_PATCH_TICK_INTERVAL: float = 1.0 # BALANCE: seconds between damage ticks

# --- Call of the Void (Corpse Bloom kill spawn) ---
const CALL_OF_VOID_RADIUS: float = 40.0          # BALANCE: contact radius in world units
const CALL_OF_VOID_STACKS: int = 3               # BALANCE: contacts before depletion
const CALL_OF_VOID_BLIGHT_RATIO: float = 0.75    # BALANCE: fraction of VILLAGER_BASE_HP per contact
const CALL_OF_VOID_SLOW: float = 0.3             # BALANCE: additive movement slow fraction
